#! usr/bin/env node

/** Websockets */
function websockets(io){

    io.on('connection', socket => {

        console.log('io',socket.request.connection)
        console.log('websockets', 'connected');

        socket.on('message', function(data) {
            
            console.log('websockets', data);

            //data.type = "outgoing"
            //socket.emit('message', data)
            
            //data.type = "incoming"
            io.emit('message', data);

        });
        
    });

}

module.exports = websockets;
